### ISSUE TITLE
 允許手開發票的狀態：complete(完成）

### ISSUE THREAD

**Issue by robert1112** [ECPay/WooCommerce_Invoice#1]
您好

允許手開發票的狀態請改為complete(完成）！

(原因)目前是processing才會顯示開立發票按鈕，但若訂單是超取付款，訂單狀態是從on hold--->complete，不會有processing，就沒辦法手開發票了，還是客人取貨後，就會回傳並觸發開立發票呢（如果是手開的話）？

如果是自動開立，是什麼狀態會開立發票？感謝

**Comment by AllennChang** [comment]
你好, 請跟我們技術客服團隊連絡,將安排專員協助服務您的問題, 請寄信到 techsupport@ecpay.com.tw ,再麻煩囉
