### ISSUE TITLE
發票開立失敗: Please remove CarruerNum

### ISSUE THREAD

**Issue by chienplee** [ECPay/WooCommerce_Invoice#2]
如題，約兩成左右的訂單會出現此錯誤而無法開立。

環境狀態：

WooCommerce 版本: 3.5.7
ECPay_Invoice 版本：Version 1.1.190422
Wordpress Version: 5.1.2
PHP 版本：7.2.13

<img width="209" alt="2019-09-12 (2)" src="https://user-images.githubusercontent.com/16417906/64788127-6ce7e380-d5a4-11e9-8243-1726a9b42a03.png">

**Comment by AllennChang** [comment]
您好, 感謝您的發問,  因你的問題需要進一步查詢,  才能了解問題發生的原因, 請協助寫信到 techsupport@ecpay.com.tw 信箱, 我們將會有專員會協助您
